/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux Jonathans-PC 5.15.167.4-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Tue Jan 14 08:45:15 IST 2025"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
